### ISSUE TITLE
Query about interplanetary navigation feature

### ISSUE THREAD

**Issue by awesomebjt** [CISprague/Astro.IQ#2]
I stumbled on this while trying to find an existing tool for artificial intelligence that calculated interplanetary trajectories. I see that mentioned in your README but with an empty checkbox next to it. Is that feature forthcoming or is this project not maintained anymore?

**Comment by cisprague** [comment]
Indeed, it is, but in another edition; development on Astro.IQ is halted
for the moment. The new version will have a C++ back end and Python
frontend, and will thus be much faster but yet still intuitive to use.

I'm researching now at the European Space agency with Dario Izzo, and in
fact I've already trained a neural network for mass-optimal planet to
planet transfers. I've added several things to PyKEP that enable this
process: pykep.pontryagin and pykep.trajopt.indirect. These tools allow you
to optimise interplanetary trajectories via the indirect method, which
helps to generate a very accurate database, from which to train a neural
network.

On 14 Nov 2017 8:20 pm, "Benjamin Thompson" <notifications@github.com>
wrote:

I stumbled on this while trying to find an existing tool for artificial
intelligence that calculated interplanetary trajectories. I see that
mentioned in your README but with an empty checkbox next to it. Is that
feature forthcoming or is this project not maintained anymore?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cisprague/Astro.IQ/issues/2>, or mute the thread
